apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: izzportfolio
  name: izzportfolio
  namespace: izznoland-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: izzportfolio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: izzportfolio
    spec:
      containers:
      - image: izznoland/izzportfolio:v0.1.0
        imagePullPolicy: Always
        name: izzportfolio-web
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
